version: '3.3'

services:

  web:
    build: .
    environment:
      DB_HOST: db
      DB_USER: api_gateway
      DB_PASSWORD: your_mysql_password
      DB_NAME: api_gateway_fifo
    ports:
      - "8443:8443"

