version: '3.3'
services:
  flask:
    build: 
      context: .
      dockerfile: Dockerfile.flask
    environment:
      FLASK_APP: api_fifo_server.py
      FLASK_ENV: production
      DB_HOST: 0.0.0.0
      DB_USER: lab
      DB_PASSWORD: your_mysql_password
      DB_NAME: api_gateway_fifo

  nginx:
    build:  
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - flask
