version: '3.3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: api_gateway_fifo
      MYSQL_USER: api_gateway
      MYSQL_PASSWORD: your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    environment:
      DB_HOST: db
      DB_USER: api_gateway
      DB_PASSWORD: your_mysql_password
      DB_NAME: api_gateway_fifo
    ports:
      - "8443:8443"
    depends_on:
      - db

volumes:
  db_data:
